version: '3.9'
services:
  webapi:
    container_name: factura_bodega_app
    build:
      context: .
      dockerfile: src/devgalop.facturabodega.webapi/Dockerfile
    ports:
      - "5550:8080" # Mapea el puerto 8080 del contenedor al puerto 5550 en tu máquina
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Postgres=${ConnectionStrings__Postgres}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:18.1-alpine3.23
    container_name: factura_bodega_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Mapea el puerto 5432 del contenedor al puerto 5432 en tu máquina
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: